name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.9'

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Create db.properties file from Secrets
        env:
          SECRET_USER: ${{ secrets.DB_USER }}
          SECRET_PW: ${{ secrets.DB_PASSWORD }}
        run: |
          mkdir -p src/main/resources
          echo "db.url=jdbc:mariadb://127.0.0.1:3307/hausverwaltung?useSSL=false&allowPublicKeyRetrieval=true" > src/main/resources/db.properties
          echo "db.user=${SECRET_USER}" >> src/main/resources/db.properties
          echo "db.pw=${SECRET_PW}" >> src/main/resources/db.properties


      - name: Wait for database to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..12}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "MySQL is ready"; break
            fi
            sleep 5
          done

      - name: Run Maven tests
        run: mvn test
